### ISSUE TITLE
Displaying results on top of others plugins

### ISSUE THREAD

**Issue by tevenfeng** [danielbayerlein/zazu-github#1]
I'm using zazu-github on Ubuntu gnome 16.04, and when i type gh sth. and it will actually show github results but only show them on the bottem of the result list, right below other plugins' results, for example results from files plugin. So is there any way to solve this?

**Comment by tevenfeng** [comment]
![image](https://cloud.githubusercontent.com/assets/3694248/24087582/ab8cff26-0d5b-11e7-8d5d-80477a235d02.png)

**Comment by danielbayerlein** [comment]
@blainesch Do you have any idea?

**Comment by bayleedev** [comment]
@danielbayerlein results without an `id` are ranked below those that do have one. So just adding an `id` would rank it higher than file finder since a prefix > root level results.

http://zazuapp.org/documentation/plugins/#internal-ranking

The docs should probably be more clear about that.

**Comment by danielbayerlein** [comment]
https://github.com/tinytacoteam/zazu/issues/269

**Comment by danielbayerlein** [comment]
@tevenfeng Can you please update your plugins? I'm looking forward to your answer. Thank you 👍 

@blainesch Many thanks for the answer.

**Comment by tevenfeng** [comment]
Yes, I updated my plugins and it works good now, thanks for your work!

**Comment by tevenfeng** [comment]
And could you please tell me a bit about how could you make it response so quickly? I've written some kind of plugins like this, and I use shell to do this, so every time input string is changed, I use curl to get the json data from the api, but it turned to be very slowly. So how do you make it so fast?
